# https://github.com/reviewdog/reviewdog/blob/master/.reviewdog.yml

runner:
  govet:
    cmd: go vet -all .
    errorformat:
      # TODO: issue
      # - "%f:%l: %m"
      - "%f:%l:%c: %m"
      - "%-G%.%#"
  rubocop:
    cmd: rubocop
